# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1d1451d84536d9eb03f2f86b51608bab69d77c01b335e65b9e4e21e4910c0397c1cc9ae3c2b92b9f23db2d41b70888d3c98445db4e50c28e5a60085074c8e1bd

test:
  secret_key_base: 71d603d89eb6ef0c71800c66f2c727873b349cb805119ff4c30d2e9b0446a43c43385b862b5ae9d2a6167ed5e29dbcc45efc9976b764694c90e73dabcdad9fd8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
